[options]
addons_path = source\odoo\addons,..\o19.odooapp.cn\addons_ent
bin_path = runtime\win32\wkhtmltopdf
pg_path = runtime\pgsql\bin
data_dir = odoofile
db_host = 127.0.0.1
db_maxconn = 64
db_name = False
db_user = odoo
db_password = odoo
db_port = 5432
loglevel = debug
db_template = template0
proxy_mode = True
http_port = 8019
gevent_port = 8072
