[options]
addons_path = source\odoo\addons
server_wide_modules = base,web
bin_path = runtime\win32\wkhtmltopdf
pg_path = runtime\pgsql\bin
data_dir = odoofile
logfile = odoofile/odoo-server.log
db_host = 127.0.0.1
db_maxconn = 64
db_user = odoo
db_password = odoo
db_name =
db_port = 5432
log_level = info
db_template = template0
proxy_mode = True
http_port = 8020
gevent_port = 2072
workers = False
max_cron_threads = 2
admin_passwd = odoo

limit_memory_hard = False
limit_memory_soft = False
limit_request = False
limit_time_cpu = False
limit_time_real = False
limit_time_real_cron = False
