# 第一个实例20
upstream o20server1  {
    server 127.0.0.1:8020;
}
upstream l20server1 {
    server 127.0.0.1:2072;
}
# 第一个实例18
upstream o18server1  {
    server 127.0.0.1:8018;
}
upstream l18server1 {
    server 127.0.0.1:8072;
}
# 第二个实例18
upstream o18server2{
    server 127.0.0.1:8028;
}
upstream l18server2{
    server 127.0.0.1:8082;
}
# 第三个实例18
upstream o18server3{
    server 127.0.0.1:8038;
}
upstream l18server3{
    server 127.0.0.1:8092;
}
# 实例17
upstream o17server1  {
    server 127.0.0.1:8017;
}
upstream l17server1 {
    server 127.0.0.1:8062;
}
# 实例16
upstream o16server1  {
    server 127.0.0.1:8016;
}
upstream l16server1 {
    server 127.0.0.1:8052;
}
upstream uniserver{
    server 127.0.0.1:8080;
}

map $http_upgrade $connection_upgrade   {
  default upgrade;
  ''      close;
}

# 根据变量（host 主机）选择 upstream
map $host $oserver {
  default o20server1;
  localhost20 o20server1;
  localhost.20 o20server1;
  localhost.a201 o20server1;
  localhost.a202 o20server1;
  localhost.a203 o18server1;
  localhost18 o18server1;
  localhost.18 o18server1;
  localhost.a81 o18server1;
  localhost.a82 o18server1;
  localhost.a83 o18server1;
  localhost.o81 o18server1;
  localhost.o82 o18server2;
  localhost.o83 o18server3;
  localhost.n81 o18server3;
  localhost.n82 o18server1;
  localhost17 o17server1;
  localhost.17 o17server1;
  localhost.a71 o17server1;
  localhost.a72 o17server1;
  localhost.o71 o17server1;
  localhost.o72 o17server1;
  localhost.n71 o17server1;
  localhost.n72 o17server1;
  localhost16 o16server1;
  localhost.16 o16server1;
  localhost.a61 o16server1;
  localhost.a62 o16server1;
  localhost.o61 o16server1;
  localhost.o62 o16server1;
  localhost.n61 o16server1;
  localhost.n62 o16server1;
}

map $host $lserver {
  default l20server1;
  localhost20 l20server1;
  localhost.20 l20server1;
  localhost.a201 l20server1;
  localhost.a202 l20server1;
  localhost.a203 l18server1;
  localhost18 l18server1;
  localhost.18 l18server1;
  localhost.a81 l18server1;
  localhost.a82 l18server1;
  localhost.a83 l18server1;
  localhost.o81 l18server1;
  localhost.o82 l18server2;
  localhost.o83 l18server3;
  localhost.n81 l18server1;
  localhost.n82 l18server1;
  localhost17 l17server1;
  localhost.17 l17server1;
  localhost.a71 l17server1;
  localhost.a72 l17server1;
  localhost.o71 l17server1;
  localhost.o72 l17server1;
  localhost.n71 l17server1;
  localhost.n72 l17server1;
  localhost16 l16server1;
  localhost.16 l16server1;
  localhost.a61 l16server1;
  localhost.a62 l16server1;
  localhost.o61 l16server1;
  localhost.o62 l16server1;
  localhost.o63 l16server1;
  localhost.o64 l16server1;
  localhost.o65 l16server1;
  localhost.o66 l16server1;
  localhost.o67 l16server1;
  localhost.o68 l16server1;
  localhost.o69 l16server1;
  localhost.n61 l16server1;
  localhost.n62 l16server1;
}